version: '3'
networks:
  proxy:
    external: true
services:
  traefik:
    image: traefik
    restart: unless-stopped
    # command: --web --docker --docker.domain=docker.localhost --logLevel=DEBUG
    # command: --api --api.dashboard=true -c /dev/null --docker.domain=docker.localhost --docker --logLevel=DEBUG --docker.endpoint=unix:///var/run/docker.sock --docker.watch --entryPoints='Name:http Address::80' --defaultentrypoints=http
    command: --api --api.dashboard=true -c /dev/null --docker.domain=docker.localhost --docker --logLevel=DEBUG
    networks:
      - proxy
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
    labels:
      - traefik.port=8080
      - "traefik.frontend.rule=Host:traefik.docker.localhost"
  portainer:
    restart: always
    image: portainer/portainer
    networks:
      - proxy
    expose:
      - 9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.backend=portainer"
      - "traefik.frontend.rule=Host:portainer.docker.localhost"
    ports:
      - "9000:9000"
